json.id flight.id
json.departure_day flight.departure_day
json.departure_time flight.departure_time
json.normal_reserved_seat flight.normal_reserved_seat
json.business_reserved_seat flight.business_reserved_seat
json.base_price flight.base_price
json.plane flight.plane_name
json.plane_type flight.plane_type_name
json.shift flight.shift_name
json.flight_route flight.flight_route_id
json.flight_duration flight.flight_duration
json.flight_status flight.flight_status_name
