export const SET_TICKET_NUMBER = 'SET_TICKET_NUMBER';

export const GET_FLIGHTS_DATA = 'GET_FLIGHTS_DATA';
export const GET_ONE_WAY_FLIGHTS_DATA = 'GET_ONE_WAY_FLIGHTS_DATA';
export const GET_ROUND_TRIP_FLIGHTS_DATA = 'GET_ROUND_TRIP_FLIGHTS_DATA';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const SIGN_OUT = 'SIGN_OUT';
export const LOADING_USER = 'LOADING_USER';
export const GET_INFO = 'GET_INFO';
