export const SET_TICKET_NUMBER = 'SET_TICKET_NUMBER';

export const GET_FLIGHTS_DATA = 'GET_FLIGHTS_DATA';

export const GET_ONE_WAY_FLIGHTS_DATA = 'GET_ONE_WAY_FLIGHTS_DATA';

export const GET_ROUND_TRIP_FLIGHTS_DATA = 'GET_ROUND_TRIP_FLIGHTS_DATA';
