export const CHANGE_OUTBOUND_FLIGHT = 'CHANGE_OUTBOUND_FLIGHT';

export const CHANGE_INBOUND_FLIGHT = 'CHANGE_INBOUND_FLIGHT';

export const CHANGE_PASSENGER_DETAILS = 'CHANGE_PASSENGER_DETAILS';

export const CHANGE_STEP = 'CHANGE_STEP';

export const CHANGE_PAYMENT_METHOD = 'CHANGE_PAYMENT_METHOD';

export const CHANGE_TOTAL_PRICE = 'CHANGE_TOTAL_PRICE';
